name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ingestion, api_gateway, ml_engine]
    steps:
      - uses: actions/checkout@v4
      - name: Build ${{ matrix.service }}
        run: |
          docker build -t ${{ matrix.service }} ./backend/services/${{ matrix.service }}
