apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion
  template:
    metadata:
      labels:
        app: ingestion
    spec:
      containers:
        - name: ingestion
          image: ingestion:latest
          env:
            - name: INFLUX_URL
              value: "http://influxdb:8086"
          ports:
            - containerPort: 8000
